url: "https://www.abbystevens.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "ABBY STEVENS" # the name of your site, e.g. ACME Corp.
description: ""
